name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        angular-version: [13.1.4, 14.0.2, v15.0.3, v16.2.12, v17.2.1]
        include:
          - angular-version: 13.1.4
            devkit-version: 0.1301.4
          - angular-version: 14.0.2
            devkit-version: 0.1400.2
          - angular-version: v15.0.3
            devkit-version: 0.1500.3
          - angular-version: 16.2.12
            devkit-version: 0.1601.0
          - angular-version: v17.2.1
            devkit-version: 0.1701.0

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --package-lock-only "@angular-devkit/architect@${{ matrix.devkit-version }}" "@angular-devkit/core@${{ matrix.angular-version }}" "@angular-devkit/schematics@${{ matrix.angular-version }}" "@schematics/angular@${{ matrix.angular-version }}"
    - run: npm ci
    - run: npm run build
    - run: npm run test
