name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        angular-version: [v15.0.3, v16.2.12, v17.1.3]
        include:
          - angular-version: v15.0.3
            devkit-version: 0.1500.3
          - angular-version: 16.2.12
            devkit-version: 0.1601.0
          - angular-version: v17.1.3
            devkit-version: 0.1701.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --package-lock-only "@angular-devkit/architect@${{ matrix.devkit-version }}" "@angular-devkit/core@${{ matrix.angular-version }}" "@angular-devkit/schematics@${{ matrix.angular-version }}" "@schematics/angular@${{ matrix.angular-version }}"
    - run: npm ci
    - run: npm run build
    - run: npm run test
