# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        angular-version: [13.1.4, 14.0.2, v15.0.3]
        include:
          - angular-version: 13.1.4
            devkit-version: 0.1301.4
          - angular-version: 14.0.2
            devkit-version: 0.1400.2
          - angular-version: v15.0.3
            devkit-version: 0.1500.3

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --package-lock-only "@angular-devkit/architect@${{ matrix.devkit-version }}" "@angular-devkit/core@${{ matrix.angular-version }}" "@angular-devkit/schematics@${{ matrix.angular-version }}" "@schematics/angular@${{ matrix.angular-version }}"
    - run: npm ci
    - run: npm run build
    - run: npm run test
    - name: Coveralls
      uses: coverallsapp/github-action@v1.2.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.node-version }}
        parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
